server:
  port: 8092 # Port for the User Service instance
  forward-headers-strategy: framework # Forward headers for correct client info behind proxies

spring:
  application:
    name: payment-service # Name registered with Eureka

  # -------------------- DATABASE CONFIG --------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # -------------------- KAFKA CONFIG --------------------
  kafka:
    producer:
      bootstrap-servers: kafka-broker:9092 
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    listener:
      missing-topics-fatal: false

# -------------------- EUREKA CONFIG --------------------
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/ # Eureka server address
    fetch-registry: true
    register-with-eureka: true

# -------------------- SWAGGER CONFIG --------------------
springdoc:
  api-docs:
    path: /v3/api-docs/payment-service
  swagger-ui:
    enabled: true

