server:
  port: 8093

spring:
  application:
    name: history-service

  # ===================== DATABASE =====================
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # ===================== KAFKA =====================
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: history-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.linkdevcode.banking.history_service.event
        spring.json.value.default.type: com.linkdevcode.banking.history_service.event.TransactionCompletedEvent

    listener:
      ack-mode: manual

# ===================== LOGGING =====================
logging:
  level:
    root: INFO
    org.springframework.kafka: INFO

# -------------------- EUREKA CONFIG --------------------
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/ # Eureka server address
    fetch-registry: true
    register-with-eureka: true

# -------------------- SWAGGER CONFIG --------------------
springdoc:
  api-docs:
    path: /v3/api-docs/history-service
  swagger-ui:
    enabled: true
