server:
  port: 8091 # Port for the User Service instance
  forward-headers-strategy: framework # Forward headers for correct client info behind proxies

spring:
  application:
    name: user-service # Name registered with Eureka

  # -------------------- DATABASE CONFIG --------------------
  datasource:
    url: jdbc:postgresql://user_db:5432/banking_user_db 
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically update the database schema
    show-sql: true # Show SQL queries in the console
    properties:
      hibernate:
        default-schema: user_schema # Specify the default schema

# -------------------- EUREKA CONFIG --------------------
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/ # Eureka server address
    fetch-registry: true
    register-with-eureka: true

# -------------------- SWAGGER CONFIG --------------------
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Management API
        url: /v3/api-docs

# --------------------- JWT ------------------------------ #
jwt:
  # Base64 encoded secret key for signing JWT tokens
  secret: YmFua2luZy1taWNyb3NlcnZpY2VzLWJhbmtpbmctc3lzdGVtLWluZmVyLWJhbmstc2VjcmV0
  # Token expiration time in milliseconds (24 hours)
  expirationMs: 86400000