server:
  port: 8095

spring:
  application:
    name: voucher-service

  # ===================== DATABASE =====================
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# -------------------- EUREKA CONFIG --------------------
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/ # Eureka server address
    fetch-registry: true
    register-with-eureka: true

# -------------------- SWAGGER CONFIG --------------------
springdoc:
  api-docs:
    path: /v3/api-docs/voucher-service
  swagger-ui:
    enabled: true
